site_name: Consulta Massiva CPF
pages:
  - Introdução: index.md
  - API CPF: api_reference.md
  - FAQ: faq.md
nav:
  - Introdução: index.md
  - Como contratar: como_contratar.md
  - Guias rápidos: 
    - Como autenticar na API CPF: quick_start/#como-autenticar-na-api-consulta-cpf
    - Como usar a demonstração da API: quick_start/#como-utilizar-a-api-cpf-demonstracao
  - Demonstração: 'demonstracao.md'
  - Documentação: 
    - Códigos de retorno: 'codigos_retorno.md'
    - Campos retornados: 'campos_retornados.md'
    - Requisições com Carimbo de Tempo: 'carimbo_tempo.md'
    - Identificador opcional de Requisições: 'identificador_requisicoes.md'
  - Suporte:
    - Dúvidas - FAQ: faq.md
  - English version: 
    - Introduction: en/
    - How to contract: en/como_contratar
    - Quick start: en/quick_start
    - Demonstration*: en/demonstracao
    - API Reference*: en/api_reference
    - Image requirements: en/requisitos_imagens
    - Error codes: en/codigos_retorno
    - FAQ: en/faq.md
theme:
  name: 'material'
  logo: imgs/favicon.png
  favicon: 'imgs/favicon.png'
  language: 'pt'
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
extra_css:
  - 'css/extra.css'
