site_name: API CONSULTA DUE
pages:
nav:

  - Versão em Português:  
    - Introdução: pt/index.md
    - Como contratar: pt/como_contratar.md
    - Guias rápidos: 
      - Como autenticar na API DUE: pt/quick_start/#como-autenticar-na-api-consulta-due
      - Como usar a demonstração da API: pt/quick_start/#como-utilizar-a-api-due-demonstracao
    - Demonstração: pt/demonstracao.md
    - Documentação: 
      - Descrição dos campos: pt/descricao_campos
      - Códigos de retorno: pt/codigos_retorno.md
      - Tipos de estabelecimento: pt/tipos_estabelecimento.md
      - Porte da empresa: pt/porte_empresa.md
      - Tipos de situação especial: pt/tipos_situacao_especial.md
      - Tipos situação cadastral: pt/tipos_situacao_cadastral.md
      - Requisições com carimbo de tempo: pt/carimbo_tempo.md
      - Identificador opcional de requisições: pt/identificador_requisicoes.md
    - Suporte:
      - Dúvidas - FAQ: pt/faq.md 
theme:
  name: material
  logo: pt/imgs/favicon.png
  favicon: pt/imgs/favicon.png
  language: pt
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
extra_css:
  - pt/css/extra.css